import { execFileSync } from "node:child_process";
import { segments } from "../shared/commands.ts";

/**
 * Cheap local facts about what a risky command would touch, gathered before Jev is asked.
 *
 * The gate used to send only the command and Claude's one-line description, and the answers
 * showed it. Measured on jev-1.13: `rm -rf dist/` scored unrestorable_change 0.56 from that,
 * 0.30 once the state said dist/ is gitignored and regenerated by the build; `git reset --hard
 * HEAD~3` went from 0.46 to 0.16 once it said the commits were never pushed and the tree was
 * clean. These are exactly the facts git can state in a few milliseconds.
 *
 * Every probe is read-only, time-boxed, and optional: a failure means one fact fewer.
 */
export function bashFacts(command: string, cwd: string | undefined): string[] {
  if (!cwd) return [];
  const facts: string[] = [];
  const git = (...args: string[]): string | undefined => {
    try {
      return execFileSync("git", args, { cwd, timeout: 800, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
    } catch {
      return undefined;
    }
  };
  if (git("rev-parse", "--is-inside-work-tree") !== "true") return ["The working directory is not a git repository."];

  const branch = git("rev-parse", "--abbrev-ref", "HEAD");
  const dirty = git("status", "--porcelain");
  if (branch) facts.push(`Current git branch: ${branch}.`);
  if (dirty !== undefined) {
    facts.push(dirty ? `The working tree has ${dirty.split("\n").length} uncommitted change(s).` : "The working tree is clean: no uncommitted changes.");
  }

  for (const seg of segments(command)) {
    const w = seg.split(/\s+/).filter(Boolean);
    const at = w.findIndex((x) => x === "rm" || x === "find");
    if (at !== -1) {
      for (const path of w.slice(at + 1).filter((a) => !a.startsWith("-") && !a.includes("$")).slice(0, 4)) {
        const ignored = git("check-ignore", "-q", path) !== undefined;
        const tracked = git("ls-files", "--error-unmatch", "--", path) !== undefined;
        facts.push(
          `${path}: ${ignored ? "gitignored" : tracked ? "tracked by git (restorable from the last commit)" : "not tracked by git"}.`,
        );
      }
    }
    if (w[0] === "git" && (w[1] === "push" || w[1] === "reset" || w[1] === "rebase")) {
      const upstream = git("rev-parse", "--abbrev-ref", "@{upstream}");
      if (upstream) {
        const ahead = git("rev-list", "--count", "@{upstream}..HEAD");
        facts.push(`Upstream of ${branch ?? "HEAD"} is ${upstream}; ${ahead ?? "?"} local commit(s) not pushed there.`);
      } else if (branch) {
        facts.push(`${branch} has no upstream branch: it has never been pushed.`);
      }
      if (w[1] === "reset") facts.push("Commits removed by a reset stay reachable through git reflog (90 days by default).");
      const remoteDefault = git("symbolic-ref", "--short", "refs/remotes/origin/HEAD");
      if (remoteDefault) facts.push(`The remote's default branch is ${remoteDefault.replace(/^origin\//, "")}.`);
    }
  }
  return facts.slice(0, 12);
}
